### PR TITLE
Add WatchMate to the list of companion apps

### PR DESCRIPTION
**Pull request by azymohliad**
Hi! Now that all the essential features are implemented, would you mind including WatchMate to the list of companion apps?

### CODE REVIEW

**Review by Riksu9000 — APPROVED** [review]
I tried the app and I really like it! Another way to easily upload resources is very useful.

**Comment by JF002** [comment]
I've just tried build and run the latest version of Watchmate (from AUR on Manjaro) and it works surpringly well! BLE scan, connection, OTA, and even resources update are flawless! Thank yo so much for your work on this project!

home
ota
resources
resources2
scan

**Review by JF002 — APPROVED** [review]

**Comment by azymohliad** [comment]
Thanks a lot @JF002! Ah, I should bundle icons into the app already, so that users outside of Gnome or Flatpak won't get those ugly placeholders

**Comment by JF002** [comment]
> Thanks a lot @JF002! Ah, I should bundle icons into the app already, so that users outside of Gnome or Flatpak won't get those ugly placeholders

You're welcome :) And yes, you're right, I'm using KDE right now.

**Pull request merged**
