### PR TITLE
HeartRate: add missing HeartRateController include

### PR DESCRIPTION
**Pull request by NeroBurner**

### CODE REVIEW

**Comment by NeroBurner** [comment]
brainfarted, HeartRateController is forward declared and included in cpp file. All is good

**Comment by NeroBurner** [comment]
have to reopen because the `HeartRateController::State` enum is used in the header, so we need the include

```
[build] In file included from /home/nero/repos/pinetime/InfiniTime/src/displayapp/DisplayApp.cpp:3:
[build] /home/nero/repos/pinetime/InfiniTime/src/displayapp/screens/HeartRate.h:31:43: error: invalid use of incomplete type 'class Pinetime::Controllers::HeartRateController'
[build]    31 |         Controllers::HeartRateController::States prevState = Controllers::HeartRateController::States::Stopped;
[build]       |                                           ^~~~~~
[build] In file included from /home/nero/repos/pinetime/InfiniTime/src/systemtask/SystemTask.h:8,
[build]                  from /home/nero/repos/pinetime/InfiniTime/src/touchhandler/TouchHandler.h:3,
[build]                  from /home/nero/repos/pinetime/InfiniTime/src/displayapp/DisplayApp.h:18,
[build]                  from /home/nero/repos/pinetime/InfiniTime/src/displayapp/DisplayApp.cpp:1:
[build] /home/nero/repos/pinetime/InfiniTime/src/heartratetask/HeartRateTask.h:12:11: note: forward declaration of 'class Pinetime::Controllers::HeartRateController'
[build]    12 |     class HeartRateController;
```

**Comment by JF002** [comment]
@NeroBurner Where is this variable `prevState` declared? I can't find it in `displayapp/screens/HeartRate.h` or anywhere else in the code.

**Comment by NeroBurner** [comment]
It was a rename done in the lvgl8 branch 72c379c59632ba74934e623d5664390c51dede21

In the branch the following private member was added to the `HeartRate` class
```cpp
Controllers::HeartRateController::States prevState = Controllers::HeartRateController::States::Stopped;
```

so this PR is stale and can be closed

**Pull request closed without merging**
