### PR TITLE
WeatherService

### PR DESCRIPTION
**Pull request by Avamander**
This PR aims to implement a WeatherService for both short-term and long-term forecasting.

Currently implemented:
- [X] - QCBOR tested and works stable
- [X] - BLE service itself
- [X] - Data is received
- [X] - Fully working decoding and the parsing should detect/avoid most common mistakes
- [X] - Getters for any watchapps/faces that want the data (Improved API for watchfaces according to what @kieranc suggested)
- [X] - Developer only textual UI, accessible with a small modification, it's not for end-users (rebasing on latest `develop` made it work when running `mcuboot-app`, don't ask me why)
- [X] - Full mapping of Gadgetbridge's weather provider to InfiniTime's
- [X] - Described the data format
- [X] - Testing with real data
- [x] - Update docs

Needs more work:
- [ ] - Waiting for companion feedback

Not in scope:
* Limit `std::vector` size, implement a purge algorithm for still valid events over set size
* Fully fleshing out the control channel (the timeline is self-cleaning right now, so very little use atm)
* Nice UI
* Watchface integration

Fixes https://github.com/InfiniTimeOrg/InfiniTime/issues/208

### CODE REVIEW

**Comment by Izaic** [comment]
Bump?

**Comment by Avamander** [comment]
Needs a bit of bug squashing, then it's quite ready for companion apps.

Some really neat watchface etc. integrations can come later.

**Comment by Avamander** [comment]
Writing data to the watch should now be fully testable for those wishing to develop a companion.

**Comment by Avamander** [comment]
I guess @Arsen6331, @alexr4535, @piggz you could try and take a look and see if (currently only) pushing data is sufficient and clear for you, or if you find any bugs.

**Comment by Arsen6331** [comment]
Can you please provide the format of the data I need to write, and to which characteristics? I tried to follow the code to figure it out, but the most I've done in C++ is hello world, so I cannot figure it out.

**Comment by Avamander** [comment]
@Arsen6331 Check out src/components/ble/weather/WeatherData.h#20 and src/components/ble/weather/WeatherService.h#111

**Comment by Arsen6331** [comment]
Ok, I got the characteristics. How do I enable the screen to see what I am actually doing?

**Comment by Avamander** [comment]
@Arsen6331 
> Ok, I got the characteristics. How do I enable the screen to see what I am actually doing?

I accidentally commited the changes, but now you can nicely see them here: https://github.com/InfiniTimeOrg/InfiniTime/pull/353/commits/86e21f54e1027a4b3041555a5bb072b3a97b8585

**Comment by Avamander** [comment]
@Zorvalt I'd love to discuss building https://github.com/InfiniTimeOrg/InfiniTime/pull/790 onto the timeline once this PR is merged, would you (or anyone reading here) be interested?

**Comment by Arsen6331** [comment]
I am trying to get it to accept my CBOR. This looks right to me, but it returns an error. Am I doing it incorrectly? This is for precipitation:

```
A5 // Object (5 pairs)
    64 // UTF-8 string (length 4)
        74797065 // "type"
    05 // positive integer: 5
    66 // UTF-8 string (length 6)
        616D6F756E74 // "amount"
    1850 // positive integer: 80
    67 // UTF-8 string (length 7)
        65787069726573 // "expires"
    190E10 // positive integer: 3600
    69 // UTF-8 string (length 9)
        6576656E7454797065 // "eventType"
    01 // positive integer: 1
    69 // UTF-8 string (length 9)
        74696D657374616D70 // "timestamp"
    1A61AB49EB // positive integer: 1638615531
```

**Comment by Zorvalt** [comment]
Yes, absolutely @Avamander :-)

**Comment by Avamander** [comment]
@Arsen6331 Capitalize the keys, I think

**Comment by Arsen6331** [comment]
> @Arsen6331 Capitalize the keys, I think

Ok, that works. Thank you. You should add that to the comment in src/components/ble/weather/WeatherData.h

**Comment by Arsen6331** [comment]
I have all the events working. This is actually very simple once I figured out what to do.

**Comment by Avamander** [comment]
@Arsen6331 Anything you miss? Manipulations you'd like to do on the timeline from the companion side?

**Comment by Arsen6331** [comment]
> @Arsen6331 Anything you miss? Manipulations you'd like to do on the timeline from the companion side?

I just finished adding events, and it was 4 AM here. I will be trying out the rest today, and will tell you if there's anything I think should be changed.

**Comment by Arsen6331** [comment]
Also, do you mind me copying your enum comments for use in my library?

**Comment by Avamander** [comment]
@Arsen6331 
> Also, do you mind me copying your enum comments for use in my library?

No, but retain the license header please.

**Comment by ItzSwirlz** [comment]
Just make sure there is a way to have it only run/work/be enabled when Gadgetbridge is active and linked. (InfiniLink is still in development for IOS stuff)

**Comment by Arsen6331** [comment]
> @Arsen6331 Anything you miss? Manipulations you'd like to do on the timeline from the companion side?

This is enough for me to work with. There is some data I may not be able to fill, but most of it should be fine. I've implemented it in my library locally, so I can test any changes and such easily. I will also be trying to implement it locally in ITD so I can see what it would take. Thank you.

**Comment by Avamander** [comment]
@ItzSwirlz

> Just make sure there is a way to have it only run/work/be enabled when Gadgetbridge is active and linked. (InfiniLink is still in development for IOS stuff)

If left unpopulated, the components fetching data from the Timeline should check for reserved and zero values and gracefully fall back.

**Comment by piggz** [comment]
Thought ... all the Timeline classes ... as theyre just public data members, wouldnt it be better to make them structs?  Only difference is structs are public by default and youre setting everything public anyway.

**Comment by Avamander** [comment]
@piggz In theory one could, but I don't see much benefit from that. It's just limits our options a bit, preemptively. Structs don't allow constructors for example, and it'd be a bit annoying to go changing it around once that is determined to yield nicer code.

**Comment by Avamander** [comment]
@piggz 

> Actually they do ... 

Ooh, my misconception.

> depends if you think there will be functions added, and private members, of if theyre just structures used for data transfer.

Not out of the question. The first thing that comes to mind is that someone might wish to add a `getFahrenheit()` to Temperature or `getBeaufort()` to Wind. 

In the end it should be fine?

**Comment by devnoname120** [comment]
@Avamander Which app do you use as a provider? The [weather is disabled for InfiniTime](https://codeberg.org/Freeyourgadget/Gadgetbridge/src/commit/0349b2530fd29c02ad4d7fa85c4144b8cf7c1457/app/src/main/java/nodomain/freeyourgadget/gadgetbridge/devices/pinetime/PineTimeJFCoordinator.java#L124-L127) on the official GadgetBridge.

**Comment by Avamander** [comment]
@devnoname120 Upstream GB doesn't have weather sending-remapping at the moment, I wrote my own. I couldn't upstream it because I couldn't get TWG to send weather intents (I can't test receiving actual intents).

Siglo has some support available I think.

**Comment by Arsen6331** [comment]
ITD also sends the weather every hour or upon running a command for any location you configure in the config file.

**Pull request merged**
