### PR TITLE
New documentation site running off of Github Pages

### PR DESCRIPTION
**Pull request by nobodywasishere**
You will also need to turn on Github Pages for this site to work properly. [link](https://nobodywasishere.github.io/Pinetime/docs/contribute/documentation.html#enabling-github-pages). I'd also recommend removing the `/doc` folder as it is redundant with this commit, but I didn't want to do that in case you had other plans for it.

I have a copy of the site running here: [https://nobodywasishere.github.io/Pinetime/](https://nobodywasishere.github.io/Pinetime/)

All feedback and constructive criticism welcome.

### CODE REVIEW

**Comment by Avamander** [comment]
@nobodywasishere Would a custom index.html be doable? Infinitime has a custom domain name and it would be great if these efforts could be consolidated.

Also, could you maybe edit git history so that it doesn't contain merge commits, e.g. rebase? Just asking this because it's important to keep the commit log clean because it's pretty much immutable after merge, as you probably know.

**Comment by nobodywasishere** [comment]
@Avamander 

Re: custom index.html, I do see there's a documentation section on the current site at https://infinitime.io/ (though empty). How would you feel about moving everything from that site to this one? It should be easy to create a blog section and such. I don't know how you feel about switching to Jekyll from Hugo though. Light vs dark theme also doesn't matter to me. 

Re: git history, I'd be fine with a large squashed commit.

Also, how do you feel about the new logo? I recreated the original as an svg (instead of a png). If you don't like it or want to stick with the original that's fine with me. I have no personal attachment to anything I've done here.

**Comment by nobodywasishere** [comment]
I wrote out blog functionality and copied one over from the current site to see how it would look. I also made it so if we do end up switching over to this website, none of the links to blog posts will need to be changed.

**Comment by JF002** [comment]
Hi @nobodywasishere and thanks for this PR. The documentation site looks beautiful and probably more organized than random .md files from the repository. I'm really happy that the documentation of this project receives some love ;)

There are already 2 pending PR regarding the documentation : https://github.com/JF002/Pinetime/pull/143 and https://github.com/JF002/Pinetime/pull/138 and I haven't had the time yet to decide how I would like to manage the documentation of the project : keep .md files in the source code, use github pages, Doxygen, an external service, an external CMS,...

So I guess now is the time to think about it!

For now, the documentation consists in .md file included in the code base because... it's easier : markdown is really simple to write, read and display, and you don't need any other service, software or technology to maintain and render it. Plus we don't need the handle the versioning of the documentation as it is tightly coupler with the source code versioning.

Same for the website (https://infinitime.io). I chose Hugo because I know it (just a little bit honestly) and because it just requires an http web server. No Node, no pgsql, no 10 containers docker-compose running on a k8s cluster hosted on AWS and no (free)external service that will one day or another modify their free policy or just close. This way I (or anyone else) can easily selfhost it on their server. I can even publish the source code of the website if you're interested to have a look :)

But I agree, this solution has some limitations and the documentation could probably be more organized and accessible.

So, assuming I don't know what Jekyll is and that I have never used Github pages, could you elaborate what you did and how it works?

**Comment by nobodywasishere** [comment]
Thank you @JF002!

If you didn't know, Jekyll is a static website generator, meaning it can take source files such as those written in markdown, and turn them into a full fledged website. Github Pages is free website hosting provided by Github for projects such as this, and it natively uses Jekyll (though it is possible to use other generators, it just doesn't work as well). I currently use Github pages for 3 other websites ([here](https://seaofgreed.com/) and [here](https://nobodywasishere.github.io/vhdlref/) for example). I also share your feeling regarding the simplicity of static websites, and Jekyll sites can be self-hosted in much the same way (using Github for hosting just makes it easier).

For this, I started by creating a template Jekyll site with the [Just the Docs](https://pmarsceill.github.io/just-the-docs/) theme. The Just the Docs theme looked really good for what I had in mind, and using it as a base saved me a lot of time writing the website.

I then collected all the available documentation within the repo (basically all of the *.md s) so I would know what information would be represented on the website, and make sure I didn't miss anything. I organized this information into different categories as follows:
- `gettingStarted` - All the basic information about how to get started using the PineTime
- `develop` - All the information regarding developing InfiniTime or developing on the PineTime
- `build` - How to build
- `flash` - How to flash
- `debug` - How to debug
- `releases` - Information about releases of InfiniTime
- `contribute` - How to contribute to the project
- `companionApps` - Information about various companion apps
- `arch` - Various pages about the architecture of the pinetime or other technical topics

(This is also the folder structure for how the docs are stored within the website)

I then took these files and basically dropped them into place within the Jekyll site (within the `/docs` folder), renaming and splitting files as necessary. I also went through and fixed links to other pages and images, and fixed typos and grammatical errors where I found them. 

Here are some explanations for how the website is setup. 

The root directory of the website is under the `/docs` folder. Everything for the website is within this folder and maintained alongside the source code.
`_config.yml` is the configuration file for Jekyll, where you set information about the website. 
`Gemfile` is where you set the plugins used by the website as well. 
The `/docs/docs` folder is where all of the documentation files are, sorted into folders as shown above. Each of these folders has an `index.md` as the parent page of that section, with some child pages alongside it. These child pages are the ones that show up on clicking the down arrow to one of the topics in the sidebar on the website. 
`assets` contains all of the images.
`_layouts` currently only contains the default layout for blog posts.
`_posts` is where all the current blog posts go.
`assets/css` and `_sass` contain some of the custom CSS for colors on the website, as well as centering images and adding image borders and such.

Pages in Jekyll have configuration information at the top, here's an example from `/docs/docs/build/index.md`:
```
---
layout: page
title: Build
has_children: true
nav_order: 20
---
```
`layout` chooses the layout for the page to be rendered in. Use `page` for pages like this and `post` for blog posts.
`title` sets the title of the page
`has_children` is specific to Just the Docs (JtD), and lets JtD know if this page has child pages that point to it
`nav_order` is also specific to JtD and sets the order of this page relative to the others, listed in on the sidebar
Other pages will have other configuration stuff at the top. 

I also added a page with some information about creating and modifying pages to the site itself [here](https://nobodywasishere.github.io/Pinetime/docs/contribute/documentation.html).

While making the website and messing with themes, as the current logo doesn't have a transparent background, the colors didn't match and the logo stood out. I had the choice of either trying to remove the background and invert the text color with GIMP, or try recreating the logo as a vector image to make things like this easier to do in the future, and so I went with the latter. 

I hope everything I've said makes sense, and I'd be happy to explain stuff if something doesn't make sense.

**Comment by pfeerick** [comment]
PR#138 is nothing compared to this, and I'll happily trash it for this to get implemented instead. 

It get my vote as far as it takes the existing markdown documents, adding the bits to instruct Jekyll what to do when generating the website, thus leaving them usable for offline use if you don't want to run the site up locally. doxygen is fine, for source code generation, but to my mind, that means all of the source code need to be documented for it to be useful, and it really is just that - source code documentation - with some extras - ie. like https://nrf24.github.io/RF24/ . That is still worth examining / considering, but doesn't replace the docs folder and this PR.

**Comment by nobodywasishere** [comment]
@JF002 Apologies if I posted a lot of information at once with my previous comment, I tried to be as thorough as possible. I just wanted to check-in, though I understand if you've been busy. Do you have any thoughts or feedback regarding my reply or the current state of this PR/site?

**Comment by nobodywasishere** [comment]
So in the interest of making this easier to use directly without Jekyll, and to not have two copies of the documentation, I've decided to rework this a little. This now builds directly out of the old doc/ folder instead with little modification to the source files (I had to rename it to docs/ though for the sake of github pages). 

As well:
- `index.md` is a copy of the main `README.md` with minor modifications to fix links (this can be changed)
- Moves the images folder inside the docs for the website to use (meaning don't have to duplicate image locations)
- Light theme instead of dark theme as it looks better
- Removed the blog section (can be added back easily)
- Need to figure out best order for navigation sidebar (as its currently alphabetical)

The site is viewable here: https://blog.eowyn.net/InfiniTime/

**Comment by pfeerick** [comment]
That looks really nice! :)

**Comment by JF002** [comment]
A new documentation is in the work in #838. Github pages were mentioned, by we decided to use ReadTheDoc instead.

**Pull request closed without merging**
