### PR TITLE
Disable sleep while in Paddle app

### PR DESCRIPTION
**Pull request by stoehraj**
Paddle.cpp: Added systemTask to disable sleeping in the constructor and
re-enable sleeping in the destructor.  Reformatted constructor function
header to match that of FlashLight.cpp due to added length.

Paddle.h: Added include for SystemTask.h.  Added SystemTask parameter to
constructor function prototype and added a private SystemTask variable.

DisplayApp.cpp: Added systemTask pointer to make_unique() function call.

### CODE REVIEW

**Comment by stoehraj** [comment]
Problem mentioned in issue #398

**Comment by Riksu9000** [comment]
InfiniTime won't sleep while touching the screen anymore after #492 was merged, so this isn't necessarily needed anymore.

**Comment by Dudemanjude** [comment]
I would still find this useful, as the screen will often timeout for me in the Paddle app, because I like my screen timeout set to 5 seconds.

**Comment by Riksu9000** [comment]
It is true that the timeout should be longer than 5s while in the paddle game, but by disabling sleep altogether, there is the danger of forgetting to close it and the battery draining quickly. This is also an issue with Flashlight currently, and it should be fixed. There needs to be a more complete solution to this.

Closing due to inactivity.

**Pull request closed without merging**
