### PR TITLE
Counter icons

### PR DESCRIPTION
**Pull request by 0x0000ff**
InfiniSim_2022-06-23_141708

### CODE REVIEW

**Comment by 0x0000ff** [comment]
Mislabeled the first commit. It didn't change the icons itself.

**Comment by Riksu9000** [comment]
What's the motive for changing this?

**Comment by 0x0000ff** [comment]
It was part of the initial changes I made to the timer. I think it makes the screen a bit tidier and the buttons look like the standard button for moving graphical objects.
numberbox-spinbutton-inline

**Comment by Riksu9000** [comment]
I don't think there's a standard. I'll close this as I don't think there's enough justification to change it and I think arrows may make it seem like it's draggable, which it's not.

Kuvakaappaus - 2022-07-22 07-39-08

**Pull request closed without merging**
