### PR TITLE
Redesign incoming call notification

### PR DESCRIPTION
**Pull request by PhilDevProg**
This pull request redesigns the incoming call notification:
IMG_20211030_112349
This pull request also adds a setting for setting the design of the incoming call notification.
IMG_20211030_112306
IMG_20211030_112326

Needed:
- [X] Redesign incoming call notification

Nice to have  (should we really make it customizable?):
- [x] Add setting to set the design of the incoming call notification
- [ ] Add setting to disable/enable the accept call button

### CODE REVIEW

**Comment by Avamander** [comment]
Could the call setting also contain a checkmark to disable the button that was requested (can't recall which, sorry)?

**Comment by PhilDevProg** [comment]
> Could the call setting also contain a checkmark to disable the button that was requested (can't recall which, sorry)?

I don't know which button you mean. Do you mean the mute button?

**Comment by Avamander** [comment]
> I don't know which button you mean. Do you mean the mute button?

It was the `Accept Call` button, finally found the discussion, because not everyone wants to use it.

**Comment by PhilDevProg** [comment]
> > I don't know which button you mean. Do you mean the mute button?
> 
> It was the `Accept Call` button, finally found the discussion, because not everyone wants to use it.

This should perhaps be done in another pull request.

**Comment by PhilDevProg** [comment]
> > I don't know which button you mean. Do you mean the mute button?
> 
> It was the `Accept Call` button, finally found the discussion, because not everyone wants to use it.

After I figured out how to import the settingsController into the Notifications.cpp file, or someone tells me, I could do it here if you want but I'm very new to C++ and InfiniTime so many questions might come. 😅

**Comment by mruss77** [comment]
@PhilDevProg to access the Settings controller in Notitifications.cpp, you'll need to update the Notifications constructor so it accepts a reference to Settings, just like how it currently accepts references to NotificationManager, AlertNotificationService, etc.:

https://github.com/InfiniTimeOrg/InfiniTime/blob/72900ca8aadfa49978a4aea3a4d88c3de6a73821/src/displayapp/screens/Notifications.cpp#L11-L16

Then in DisplayApp.cpp you'll need to update the line that instantiates the Notification screen to pass in settingsController as a parameter:

https://github.com/InfiniTimeOrg/InfiniTime/blob/72900ca8aadfa49978a4aea3a4d88c3de6a73821/src/displayapp/DisplayApp.cpp#L348-L357

Looks like there are two calls to Notifications there that need to be updated (one for when the Notification opens briefly in "preview" mode).

Hope this helps.

**Comment by PhilDevProg** [comment]
> @PhilDevProg to access the Settings controller in Notitifications.cpp, you'll need to update the Notifications constructor so it accepts a reference to Settings, just like how it currently accepts references to NotificationManager, AlertNotificationService, etc.:
> 
> https://github.com/InfiniTimeOrg/InfiniTime/blob/72900ca8aadfa49978a4aea3a4d88c3de6a73821/src/displayapp/screens/Notifications.cpp#L11-L16
> 
> Then in DisplayApp.cpp you'll need to update the line that instantiates the Notification screen to pass in settingsController as a parameter:
> 
> https://github.com/InfiniTimeOrg/InfiniTime/blob/72900ca8aadfa49978a4aea3a4d88c3de6a73821/src/displayapp/DisplayApp.cpp#L348-L357
> 
> Looks like there are two calls to Notifications there that need to be updated (one for when the Notification opens briefly in "preview" mode).
> 
> Hope this helps.

@mruss77 Thank you. I'll try that later.

**Comment by PhilDevProg** [comment]
@mruss77 Unfortunately that doesn't work. I get this error message:
Screenshot from 2021-11-12 14-32-32

**Comment by mruss77** [comment]
Looks like maybe the declaration of the constructor in Notifications.h was not updated to include the new parameter that was added in Notifications.cpp? I didn't mention that, but that's another thing you would need to change.

**Comment by PhilDevProg** [comment]
@mruss77 Thank you. Most of the bugs have now been resolved. Only that appears:
Screenshot from 2021-11-12 14-51-02

**Comment by mruss77** [comment]
That one is less clear to me... could be a similar issue with the function call not matching the parameters defined in the header... have you made changes to NotificationItem?

**Comment by PhilDevProg** [comment]
@mruss77 Yes, I did. After I removed the canges I made to NotificationItem only this error appears: 
Screenshot from 2021-11-12 15-20-56

**Comment by PhilDevProg** [comment]
@mruss77 I removed the changes I made in NotificationItem but no these errors appears:
Screenshot from 2021-11-12 15-25-16

**Comment by mruss77** [comment]
Do you have your most recent code uploaded to GitHub? It would be good for us to look over the whole thing and see where the underlying issue is.

**Comment by PhilDevProg** [comment]
@mruss77  I'll do that now.

**Comment by mruss77** [comment]
OK, I see the problem now. NotificationItem is a subclass of Notifications. It doesn't automatically have access to the members of its parent (like settingsController, which you're trying to access here).

The simple fix is to basically replicate the changes you made to Notifications in NotificationItem - change the constructor to accept a reference to Settings, and then update all the calls to the constructor to pass in settingsController.

Another way to handle this would be to have NotificationItem accept a reference to its parent Notifications object, and have it access Settings and AlertNotificationService through its parent, but then you would have to add "getter" functions to Notifications as well.

I hope this makes sense... I am learning C++ myself and was not aware of this problem until you ran into it.

**Comment by PhilDevProg** [comment]
@mruss77 Thank you. Do you know where and how I can change the constructor? I never programmed C++ before. 😅

**Comment by mruss77** [comment]
Sure, the constructor for NotificationItem starts on line 145 in Notifications.cpp. You'll also have to update the declaration in Notifications.h (starts on line 34).

Then you'll need to find all the places where a NotificationItem is created (I see 4 of them in Notifications.cpp) and add that parameter. Look for calls to std::make_unique to find them.

**Comment by PhilDevProg** [comment]
@mruss77 Thank you very much! It now works!

**Comment by Riksu9000** [comment]
I don't know if we need this screen specifically to be customizable and I think the current design fits the rest of the UI better judging by the pictures provided at least.

**Comment by PhilDevProg** [comment]
> I don't know if we need this screen specifically to be customizable and I think the current design fits the rest of the UI better judging by the pictures provided at least.

Maybe you're right...
But InfiniTime doesn't look very good at the moment, and developers don't have any design suggestions to go by. So how about if there is a repository where users and developers discuss the design of InfiniTime and if someone can create mockups to upload them. What is discussed in the repository could then be used to guide developers.

**Comment by Avamander** [comment]
> and developers don't have any design suggestions to go by.

Consistency is the key for now.

> how about if there is a repository where users and developers discuss the design of InfiniTime and if someone can create mockups to upload them. What is discussed in the repository could then be used to guide developers.

You can create a new issue about this, that can be used for discussion. Though I think there might already be one. Redesigns in general are conflict prone and that's why it's better to start from discussion than implementation.

**Comment by PhilDevProg** [comment]
> You can create a new issue about this, that can be used for discussion. Though I think there might already be one.
> 

Do you mean an issue for the repository idea or issues for redesigns?

**Comment by Avamander** [comment]
@PhilDevProg 
> Do you mean an issue for the repository idea or issues for redesigns?

Issues for establishing guidelines for redesigns, I guess.

**Comment by PhilDevProg** [comment]
> Issues for establishing guidelines for redesigns, I guess.

Do you mean something like GNOME's Human Interface Guidelines?

**Comment by Avamander** [comment]
@PhilDevProg 

Yes, but without the assumption that the user is stupid and has bad eyesight.

**Comment by PhilDevProg** [comment]
@Avamander I have created Issue #892.

**Comment by PhilDevProg** [comment]
I close this because so much has changed in the Infinitime code that there are so many conflicts that it would be very difficult to rebase the code of this pull request. If someone from the InfiniTime developer team wanted me to recreate my design with the current code I would do that for sure.

**Pull request closed without merging**
