### PR TITLE
Memory savings by replacing strings

### PR DESCRIPTION
**Pull request by Riksu9000**
Saves 996 bytes!

### CODE REVIEW

**Comment by JF002** [comment]
@Riksu9000 Impressive! Does it free RAM or FLASH memory?

**Comment by Riksu9000** [comment]
> @Riksu9000 Impressive! Does it free RAM or FLASH memory?

These changes only free FLASH memory.

**Comment by JF002** [comment]
How come those std::to_string were using so much space in flash?

**Comment by geekbozu** [comment]
there are still a few more instances of `std:to_string` left in the repo it seems. In the date time library. I wonder if removing those will yield some more space? I'm confused as well as to why this frees up so much room. Is it just because we no longer link to_string in the infinitime blob? Or is that just that hungry of a routine...in flash?

**Pull request merged**
