### PR TITLE
Update Date&Time settings label for "Date & Time"

### PR DESCRIPTION
**Pull request by ajira86**
Proposal to update Date&Time label for issue #1746

image

### CODE REVIEW

**Review by NeroBurner — APPROVED** [review]
Minimal change. Looks good. A rebase and conflicts resolved would be nice

**Comment by JF002** [comment]
I'm OK with this change, thanks @ajira86  for your contribution! 

I'm not sure why the CI is red for build-firmware, build-simulator and test-clang-tidy for such a small change. But since there's a conflict, I tried editing the PR by rebasing on main (since I'm suppose to have this privilege), but I honestly don't know how to make this right.

@ajira86 could you rebase you change on main so we can merge it? 
Or does anyone know how to correctly edit a PR from a contributor?

**Review by JF002 — APPROVED** [review]

**Comment by mark9064** [comment]
If the ajira has "repository maintainers can edit this PR" or whatever the option is turned on, you should be able to (force) push directly to their branch IIRC. To do that you just clone their branch as usual and then push onto it, my preferred workflow is to add it as a new remote

**Comment by JF002** [comment]
When I checkout the @ajira86 's branch, it's checked out as a detached head, so I'm not sure I can push it after I fix the conflict.

**Comment by FintasticMan** [comment]
I've pushed it!

**Comment by JF002** [comment]
@FintasticMan Thanks! :+1 I'll need to learn this feature from Github!

The action build-firmware failed because of the "/" in the branch name so that's not an issue. I'll merge it!

**Pull request merged**
