### PR TITLE
Fix recovery firmware build

### PR DESCRIPTION
**Pull request by evergreen22**
Fix the "recovery" firmware build targets

Error introduced in #746

### CODE REVIEW

**Comment by JF002** [comment]
@evergreen22 Why did you reopen this PR? The [last build](https://github.com/InfiniTimeOrg/InfiniTime/actions/runs/1402602746) on develop succeeded.

**Comment by evergreen22** [comment]
I reopened because building recovery targets didn't work for me. The compiler looked in the systems folders for the BootErrors.h file instead of locally. The CI build works, but I don't think it is building any of the recovery targets.

**Comment by evergreen22** [comment]
I can see that the recovery target is building on CI (wasn't logged in to GH when I replied before). All I can say is that the recovery targets will not build on my local machine unless the change in this PR is made.

**Comment by JF002** [comment]
Ok, I got confused by the new colors in Github. I thought you re-open PR that was already merged...
I had a look at the changes, and they make sense, I'll merge it ;)
I'm not sure why it works on github/docker/my setup and not on your side, though.

**Pull request merged**
