### PR TITLE
Reduce repeated code for watchface list render

### PR DESCRIPTION
**Pull request by sigseg5**
I reduced the amount of code in SettingWatchFace.cpp to improve code readability and convenience, so now when adding a new watchface, you won't have to copy many lines of code.

### CODE REVIEW

**Comment by hatmajster** [comment]
I think You can also remove `optionsTotal` and just use `i` in Your loop

**Comment by sigseg5** [comment]
> I think You can also remove ~optionsTotal~ `watchFaceCount` and just use `optionsTotal`. Also just use `i` in Your loop

Updated, I think it's OK due to some limitation like `Variable-sized object may not be initialized` etc.

**Comment by Avamander** [comment]
It's okay and probably safer to use `std:string` instead of C-style string/array.

**Comment by sigseg5** [comment]
> probably safer to use `std:string` instead of C-style string/array

I think that `const * char watchFaceNames[watchFaceCount]` is safe enough in this context. Indeed I could use std::string, so the code would be more uniform (and probably safer in the future). But on the other hand, using std::string does bring a small performance degradation, you may want to take a look at this [asm](https://godbolt.org/z/fW319PYbo). What ideas do you have about it that would be more appropriate to use?

**Comment by Riksu9000** [comment]
A similar enhancement has been merged.

**Pull request closed without merging**
