### PR TITLE
Build using Travis

### PR DESCRIPTION
**Pull request by danielkucera**
plus some include fixes

### CODE REVIEW

**Comment by danielkucera** [comment]
Shit, I didn't notice there is one PR like this already...
Anyway, this one also does releases like here:
https://github.com/danielkucera/Pinetime/releases/tag/untagged-bad0f427aa9280d87c03
on tagged releases it looks better.

**Comment by incyi** [comment]
Why do you use arm-none-eabi-gcc from https://armkeil.blob.core.windows.net ? Is this an official link ?

**Comment by danielkucera** [comment]
Yes, it's link  from ARM page:
```
$ curl 'https://developer.arm.com/-/media/Files/downloads/gnu-rm/8-2019q3/RC1.1/gcc-arm-none-eabi-8-2019-q3-update-linux.tar.bz2?revision=c34d758a-be0c-476e-a2de-af8c6e16a8a2?product=GNU%20Arm%20Embedded%20Toolchain%20Downloads,64-bit,,Linux,8-2019-q3-update'
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/8-2019q3/RC1.1/gcc-arm-none-eabi-8-2019-q3-update-linux.tar.bz2">here</a>.</h2>
</body></html>
```

**Comment by geekbozu** [comment]
Is this needed anymore now that we have Github builds working @JF002?

**Comment by JF002** [comment]
I think we can safely close this one as we've finally have Github builds, indeed. If anyone wants to add and maintain an alternate CI, feel free to open a new PR :)

**Pull request closed without merging**
