### PR TITLE
Add airplane mode feature

### LINKED ISSUE #632: Disable Bluetooth
Hi - is there a way to disable bluetooth from the watch?  If not, could it be added as a feature request?

### PR DESCRIPTION
**Pull request by evergreen22**
~~# Add airplane mode feature~~

Refactor the code for style in preparation for adding an airplane mode feature. More design work needs to be done.

### CODE REVIEW

**Comment by yehoshuapw** [comment]
Maybe recovery should ignore this, otherwise if there is some error, while this is on - you cannot update the firmware over Bluetooth.

**Comment by ItzSwirlz** [comment]
I personally think we just need better options with the Bluetooth (choose connections to connect to). It would make things easier

**Comment by Itai-Nelken** [comment]
The 'firmware' and 'about' settings sbould be at the bottom as they are the least used setting in my opinion.

**Comment by lman0** [comment]
@evergreen22   can you add a plane icon  when in "airplane mode" that replace the bluetooth icon?
in the the digital watchface first (and maybe other watch if you want/can ).

thanks


the reason :
because , when i on a plane i deactivate the bluetooth of my phone , then  the bluetooth icon disappear on infinitime yet it's still advertise.
having a icon for airplane mode would be helpfull and less stressfull (i would not have to check every time if i'm on airplane mode , in the seting)

**Comment by uis246** [comment]
> I personally think we just need better options with the Bluetooth (choose connections to connect to). It would make things easier

From my comment under issue:
> I think there will several modes: "noisy"(with adv), normal(without adv), quiet(if possible to use rx only) and disabled.

**Pull request closed without merging**
