### PR TITLE
BLE FS Using adafruits Simple (not fast) BLE FS  Api

### PR DESCRIPTION
**Pull request by geekbozu**
TODO:

FS Command implementation
- [x] Read
- [x] Read Pacing
- [x] Write
- [x] Write Pacing
- [x] Delete
- [x] Make Dir
- [x] List Dir
- [x] Move File/Folder

Companion/Test App
- [x] Feature Parity To Implementation

Documentation
- [x] Documentation in Infinitime For companion app developers implemented by #839 

The start of a PR to enabled access to the internal FS over a BLE characteristic. 

Discussion on merits of implementation in #750

Currently the marked features are working in this PR,
There is a deviation from the spec which states 

>Commands always start with a fixed header. The first entry is always the command number itself encoded in a single byte. The number of subsequent entries in the header will vary by command. The entire header must be sent as a unit so set the characteristic with the full header packet. You can combine multiple commands into a single write as long as the complete header is in the packet.

I expect one command per packet with no provisions for more, I could extend this to support more commands per packet...I just do not think the complexity is needed. 

I ignore and set all date time information to 0. DO not use date time for anything.

### CODE REVIEW

**Comment by Avamander** [comment]
+1 for the Adafruit protocol 😀 the even slightly bigger ecosystem will help.

**Comment by Avamander** [comment]
@geekbozu is there a blocker to this PR?

**Comment by geekbozu** [comment]
It heavily depends on my IRL schedule. There is quite a bit Todo I hope to have a task lost up today, and to continue chipping away at it! 
There are no major blockers as of the moment implementation wise. Just time to work on it.

**Comment by geekbozu** [comment]
Added a task list for this, It is slowly nearing completion!
I added some comments in the OP about deviations from the OG spec as well as asked questions about it above. 
Feedback is requested!

**Comment by geekbozu** [comment]
Move works! At this point its feature complete. It needs some better status code returns as well as some documentation. 
Have we decided where that documentation is going to live yet?

**Pull request merged**
