### PR TITLE
change step goal increment to 500

### PR DESCRIPTION
**Pull request by mashuptwice**
Change the increment of the step goal setting to 500, as requested in #1427 
InfiniSim_2022-11-12_025101

### CODE REVIEW

**Comment by minacode** [comment]
Let's reduce the magic numbers and introduce a
```cpp
static constexpr <type> stepSize {500}
```

**Comment by mashuptwice** [comment]
@minacode good point!

**Comment by mashuptwice** [comment]
Does the settings version in `src/settings/Settings.h` need to be incremented after this change?

**Comment by minacode** [comment]
I don't think so. The saved values were not touched and all old values are still valid.

**Comment by Riksu9000** [comment]
Implemented in #1575

**Pull request closed without merging**
