### PR TITLE
Issue templates to tame the wilderness

### PR DESCRIPTION
**Pull request by dyamon**
This is an example of what can be done with issue template forms in Github. With some autolabelling and a form structure it might be possible to get better structured bug reports and feature requests and avoid duplicates.

Feedback on existing or new templates appreciated.

_I haven't included PR templates but those are an option as well._

### CODE REVIEW

**Comment by JF002** [comment]
@dyamon Is it possible to how it'll actually look like? Could you provide a screenshot, maybe?

**Comment by Riksu9000** [comment]
Viewing the file on GitHub renders it probably close to what it would actually look like.

**Comment by Avamander** [comment]
These templates seem fine, no?

**Review by Avamander — APPROVED** [review]

**Comment by dyamon** [comment]
@JF002 you should be able to see the rendered version (almost) going into "Files Changed" > tree dots on on a specific file > "View file" 

If this still doesn't give a preview of the templates, I'll post some screens :)

**Comment by JF002** [comment]
@dyamon 
> @JF002 you should be able to see the rendered version (almost) going into "Files Changed" > tree dots on on a specific file > "View file"

Oh wow! I didn't know that functionality!

@Avamander 
> These templates seem fine, no?

Looks good to me :)

Just one question : should we add the possibility for the users to ask more generic questions (how to use this or that, for example) ?

**Comment by dyamon** [comment]
People will still be able to open regular issue if they wish to do so. The "New Issue" dialogue will just prioritise templates.

**Comment by JF002** [comment]
@dyamon Oh great, thanks!

**Comment by JF002** [comment]
image
Wohoo :)

**Comment by dyamon** [comment]
I noticed a small typo, but it's not worth it to open a new PR. To have the automatic label we should have
`feature request` instead of `feature-request` here:

https://github.com/InfiniTimeOrg/InfiniTime/blob/9e0a7ddf5759dd67a61c27c0f028a6cca61fe01d/.github/ISSUE_TEMPLATE/feature-request.yaml#L2-L5

**Comment by JF002** [comment]
> @JF002 I noticed a small typo, but it's not worth it to open a new PR. To have the automatic label we should have `feature request` instead of `feature-request` here:
> 
> https://github.com/InfiniTimeOrg/InfiniTime/blob/9e0a7ddf5759dd67a61c27c0f028a6cca61fe01d/.github/ISSUE_TEMPLATE/feature-request.yaml#L2-L5

Thanks, fixed in https://github.com/InfiniTimeOrg/InfiniTime/commit/90fdea29b80016c6d0e6d518853c9251555ea695 :)

**Pull request merged**
