### PR TITLE
Create a coin flip app

### PR DESCRIPTION
**Pull request by ItzSwirlz**
Hello, I'm new to the project, and I want to get involved. I was going to make a Snake game, but as a start I decided to start creating a coin flip app. (Idea in #779)

This is just a base app and doesn't do anything yet.Since I'm new feel free to critique me and leave comments!

### CODE REVIEW

**Comment by medeyko** [comment]
Thanks! However, I think it would be better to create an app supporting arbitrary sized dices. It would be useful for a lot of games.

**Comment by ItzSwirlz** [comment]
maybe eventually have a section for all the randomized stuff/apps later down the road?

**Comment by Riksu9000** [comment]
There's a dice rolling app PR which also has d2 #565

**Comment by ItzSwirlz** [comment]
If there is a dice app it should just become a general Randomizer app and have pages (swipe right to a different section, like on the main screen left to the settings)

**Pull request closed without merging**
