### PR TITLE
motion: Disable Motion app

### PR DESCRIPTION
**Pull request by Riksu9000**
This is a debugging app, not useful for most people. Also remove the app icon.

### CODE REVIEW

**Comment by JF002** [comment]
Oh wow! 6KB for this app? What's using all this space? The graph widget from LVGL, maybe?

**Comment by Riksu9000** [comment]
It must be the chart widget. LVGL things always seem like candidates for memory savings to me.

**Comment by JF002** [comment]
Interesting! Most of the time, I do not like removing features from the firmware but... this one makes sense : the memory usage for this test/debug app is not reasonable.

I'm wondering : should we provide another (simpler) test app for the motion sensor?

**Comment by Riksu9000** [comment]
I don't think removing features is a bad idea if it will improve the polish of the firmware, which removing a debug app from release firmware definitely does. I don't think a test app needs to be added, as the detected accelerometer in SystemInfo seems to usually be ??? when the accelerometer is not working #1099.

**Comment by RageGamerBoi** [comment]
Possibly just a live updating readout of the raw accelerometer values in Settings could serve the same purpose.

**Comment by JF002** [comment]
>  I don't think a test app needs to be added, as the detected accelerometer in SystemInfo seems to usually be ??? when the accelerometer is not working.

Fair enough !

> Possibly just a live updating readout of the raw accelerometer X, Y, and Z values in Settings (and Steps too, I guess) could serve the same purpose.

Yes, it could, but it won't bring any other value than checking that the sensors returns some values. As Riksu said, we can check that the motion sensor is detected in SystemInfo so we probably don't need another app for that purpose.

**Review by JF002 — APPROVED** [review]

**Pull request merged**
