### PR TITLE
Filesystem over BLE

### PR DESCRIPTION
**Pull request by redengin**
Directly plumbed to the Pinetime littlefs implementation https://github.com/JF002/Pinetime/pull/162

Expands upon the conventions of DfuService.
Provides:
* Listing of directories
* Creating directories
* Reading of a file
* Writing of a file
* Deleting files
* Deleting empty directories

### CODE REVIEW

**Comment by ZephyrLabs** [comment]
@redengin please add file system integration with LVGL (graphics library used in Infinitime)
more info here:
https://docs.lvgl.io/v6/en/html/overview/file-system.html

for more info please contact on discord/telegram/matrix of pinetime dev-channel
cheers

**Comment by Avamander** [comment]
@ZephyrLabs that's something that should probably be implemented with LVGLv7 migration, which is not a trivial amount of work.

**Comment by JF002** [comment]
Thanks for this impressive PR, @redengin !
Is this ftp service over BLE part of a standard that is/will be implemented by some companion apps?

Where you able to test the implementation (LittleFS + ftp service over BLE) with a companion app or an application/script on a pc?

**Comment by redengin** [comment]
It's over BLE GATT using a protocol similar to the DFUService. Where possible I used OBEX constants (Service UUID, opcodes).

I've not been able to test it as there is not test framework in Pinetime and as you've identified this will need a custom app (or gadgetbridge module) as there is no protocol standard for filesystems over BLE.

**Comment by JF002** [comment]
Similar feature have been implemented and merged in #438, we can close this PR.

**Comment by hubmartin** [comment]
@redengin Hi, I'm looking for solution to transfer files to/from the InfiniTime. I've added Console BLE NUS service #560 but I would rather copy files through another channel.

I've read this thread and checked the source code but cannot find any trace how to actually list directory or send file from my computer. You mention that the other part for computer needs to be written, but how did you written all that without any testing? Even if you have some python scripts, then this might help a lot for development. I'm not familiar with OBEX. Can you please create an example how to transfer a file? Thanks

**Comment by Avamander** [comment]
Implemented by https://github.com/InfiniTimeOrg/InfiniTime/pull/756

**Pull request closed without merging**
