### PR TITLE
Workflow ignore *.md files

### PR DESCRIPTION
**Pull request by mashuptwice**
Changes in any .md file should not trigger a build workflow

### CODE REVIEW

**Comment by Riksu9000** [comment]
I was hesitant to add more ignores as they have to be duplicated multiple times, but I found a solution #1279. I'd prefer that be merged first and then we can easily ignore more paths.

**Comment by Riksu9000** [comment]
@mashuptwice Can you update this PR and we'll merge it?

**Comment by mashuptwice** [comment]
@Riksu9000 merged upstream, the PR is updated.

**Comment by Riksu9000** [comment]
There are still conflicts. lv_sim.yml was removed in develop for example.

**Comment by mashuptwice** [comment]
@Riksu9000 sorry, I forgot to pull first.

**Pull request merged**
