### PR TITLE
Fix Alarm app crashing on buttonpress

### LINKED ISSUE #770: Crash when exiting alarm app with button after setting it
### 

- [x] I searched for similar bug reports and found none was relevant.

### What happened?

Exiting alarm app with button after seting it crashes InfiniTime sometimes. 

### What should happen instead?

InfiniTime shouldn't crash. 

### Reproduction steps

Open alarm app, set it, exit it with the button, watch will lock up and InfiniTime will reboot.
I haven't been able to reproduce this reliably though. Sometimes it happens and sometimes it doesn't. 

### More details?

_No response_

### Version

Develop 1d76d91 (with pr's #746, #740, #720, #698, #679, #747, #648, #652, #586, buy none of them change the alarm other than 698) 

### Companion app

_No response_

### PR DESCRIPTION
**Pull request by Riksu9000**
Fixes #770 

This should be fixed before releasing 1.7.0

### CODE REVIEW

**Comment by mruss77** [comment]
Thanks, I came in here to open this same PR this morning!

I've been testing the same fix for several days and the alarm is no longer crashing.

**Comment by Avamander** [comment]
Why not initialize them all to `nullptr`?

**Comment by Riksu9000** [comment]
> Why not initialize them all to `nullptr`?

Everything else gets initialized in the constructor and we don't initialize them to nullptr in other screens either.

**Comment by Avamander** [comment]
> Everything else gets initialized in the constructor and we don't initialize them to nullptr in other screens either.

Do you have any ideas how such uninitialized variables could be better avoided? Any warnings?

**Review by Avamander — APPROVED** [review]

**Comment by Riksu9000** [comment]
> > Everything else gets initialized in the constructor and we don't initialize them to nullptr in other screens either.
> 
> Do you have any ideas how such uninitialized variables could be better avoided? Any warnings?

There was a warning that the constructor doesn't initialize those variables.

**Comment by Avamander** [comment]
> There was a warning that the constructor doesn't initialize those variables.

What was the name? Maybe it should be turned into an error with `-Werror=<name>`.

**Comment by Riksu9000** [comment]
> > There was a warning that the constructor doesn't initialize those variables.
> 
> What was the name? Maybe it should be turned into an error with `-Werror=<name>`.

Oh not a compilation warning but a clang-tidy one. This one https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-pro-type-member-init.html

**Review by geekbozu — APPROVED** [review]

**Comment by ncartron** [comment]
Hi, I had a pre 1.7 DFU without this PR and the Alarm app was constantly crashing.
I confirm that with a DFU which includes that PR, the Alarm app works as expected, no more crash ! <3

**Comment by petterhs** [comment]
PR is fixing the issue :+1:

**Review by petterhs — APPROVED** [review]

**Comment by JF002** [comment]
Thanks! Just in time for 1.7! (Initially, I was going to release it sooner, but I was too busy these last few days...).

**Pull request merged**
