### PR TITLE
Music app redesign

### PR DESCRIPTION
**Pull request by coffandro**
I found the stock music app unsatisfactory so therefor I decided to redesign it, on my watch I've found it to be more stable than stock and it's easier to see what buttons do and such
image

### CODE REVIEW

**Comment by coffandro** [comment]
Thank you, I 100% agree, also wanted to somehow make the title more or less fill the entire  empty space but couldn't find a way to do it in LGVL

**Comment by coffandro** [comment]
Newest version provides a better layout for the song name though it does have a tendency to overflow slightly which I'm working on

**Comment by JustScott** [comment]
Loving this design! I notice that swiping up and down increases and decreases the volume, removing the ability to swipe down to exit the app. I'm not sure if this was intentional or a bug, but assuming it was intentional, I think the Infinitime developers prefer apps to not take over the swipe to exit ability (I think I saw someone say that in a PR, I may also be wrong). Anyways... I'll still be using it, thank you for the work you did on this!

**Comment by JustScott** [comment]
@coffandro I noticed you changed the notification label color in this pull request, as that's unrelated to the music app it should probably be removed.

**Comment by coffandro** [comment]
That is true, updating it in a day or so for 1.14 and ill remove it and recheck everything then

**Comment by coffandro** [comment]
> Loving this design! I noticed that swiping up and down increases and decreases the volume, removing the ability to swipe down to exit the app. I'm not sure if this was intentional or a bug, but assuming it was intentional, I think the Infinitime developers prefer apps to not take over the swipe to exit ability (I think I saw someone say that in a PR, I may also be wrong). Anyways... I'll still be using it, thank you for the work you did on this!

Pretty sure the stock music app already lock up/down, i have just adapted it for my own use case, and the one i see as more practical, where the music app "takes over" control until you press the button, can remove this if a maintainer wants me to tho

**Comment by JustScott** [comment]
> That is true, updating it in a day or so for 1.14 and ill remove it and recheck everything then

I just adapted it to 1.14 so i could merge it into my fork, you can use it if you'd like! https://github.com/JustScott/InfiniTime/tree/change_music_app_design

**Comment by coffandro** [comment]
Remaking the changes

**Pull request closed without merging**
