### PR TITLE
Improve BLE documentation

### PR DESCRIPTION
**Pull request by Elara6331**
I have noticed, during my development of [`itd`](https://gitea.arsenm.dev/Arsen6331/itd) and [`infinitime`](https://gitea.arsenm.dev/Arsen6331/infinitime), that the BLE documentation for InfiniTime is lacking. I had to spend over 2 hours scouring through Nordic documentation and InfiniTime source code just to find a couple UUIDs and a message format table. I decided to make some documentation. I posted it in my repo: [docs.md](https://gitea.arsenm.dev/Arsen6331/infinitime/src/branch/master/docs.md). I wanted more people to be able to see it, so I merged it with the existing BLE docs and fixed some spelling and grammar mistakes.

### CODE REVIEW

**Comment by JF002** [comment]
Thanks! That looks good to me!
As you may have seen, I create a PR that adds a new Motion service (https://github.com/InfiniTimeOrg/InfiniTime/pull/754) and included documentation about this service in an additional file. This way, the main page is not cluttered with many details about all the services. 

What do you think? Should we keep all the info in 1 page or create smaller pages about each service?

**Comment by Avamander** [comment]
I'm getting the feeling more and more than these paragraphs should just be JavaDoc-style inside the source code. This would reduce documentation maintenance burden and keeps relevant things tightly tied together.

**Comment by Arsen6331** [comment]
> I mean services are all very self contained and there's a few files to look at if you're interested in a single one. There's also search.
> 
> I don't think yours is a more common problem than documentation getting outdated when it's kept separate.

That is a good point, but in the absence of something like godoc, it is very inconvenient to look for docs in the source code. I think some parts of this can be put in the source code, but some, like the DFU section, are too long to place the entire thing into the code.

**Comment by geekbozu** [comment]
I'm with avamander here, a large amount of this should be in the code and generated with some documentation generator that we can link to the planned #748
I love that its getting documented period however, and any an all is welcome. Since well none is worse :D

**Pull request merged**
