### PR TITLE
WIP: SmartControl, UI is semi-ready

### PR DESCRIPTION
**Pull request by drzacek**
This is a displayapp for the "Smart Home control", with simple UI - 3 displayed sensor values and 3 buttons. 
The widgets are with dummy values now, there is no bluetooth communication at all yet.

### CODE REVIEW

**Comment by hubmartin** [comment]
Thanks, my plan is to add a BLE service and do a prototype Python BLE-MQTT gateway which could be later integrated to GadgetBridge by someone who knows how.

**Comment by hubmartin** [comment]
This PR is based on ideas in #562

**Comment by hubmartin** [comment]
Just an update on my side. I have concept of python MQTT client bridge between Watches and MQTT broker.
Right now the code is using my BLE NUS #560 service and in the end it will use antoher service (but it will be practically same like the current BLE NUS, since it will use text commands divided by some divide symbol like `;`)
https://github.com/hubmartin/InfiniTime-tools/blob/master/ble-mqtt.py

**Comment by Riksu9000** [comment]
This PR is WIP, but hasn't been updated. Without the bluetooth part, this isn't very useful for us. Closing as stale.

**Pull request closed without merging**
