### PR TITLE
Clean up contribute.md

### PR DESCRIPTION
**Pull request by muesli**
Fixes a bunch of typos, improves grammar, sticks to a consistent line
width.

### CODE REVIEW

**Comment by JF002** [comment]
Thanks for your PR!

However, it's not easy to see what was actually changed since the whole file has changed when adding new lines.
Was this really necessary? I mean most of IDE and text editor can do "soft wrap" to adapt the length of the line to you window and screen. For example, in CLion : 
image

**Comment by Avamander** [comment]
Line width should be left to the client, hard wrapping ruins display on narrow screens such as phones.

**Comment by muesli** [comment]
Similar to source code, this is a general recommendation for markdown from the CommonMark style guide. The intention is to improve readability on the terminal. Unlike source code, markdown renderers typically use soft-wraps, so the content automatically reflows and adapts to the output width (see @JF002's screenshot above for an example).

**Comment by Avamander** [comment]
> The intention is to improve readability on the terminal.

This content is not viewed only on terminals, it's also visible on web, both mobile and desktop. The age of VT-100 terminal-oriented web or text is seriously over.

**Comment by muesli** [comment]
> This content is not viewed only on terminals, it's also visible on web, both mobile and desktop. The age of VT-100 terminal-oriented web or text is seriously over.

Then you really don't need to worry, because on the web these newlines don't get interpreted. For everyone who's still on the terminal, this is generally considered an improvement.

**Comment by JF002** [comment]
I agree with  @Avamander, not everyone use terminal to view and edit markdown (or source code) files. I personally work on 2 1920x1080 display and find it irritating when a file renders on less than a third of the width available.
Doesn't terminal apps allow to softwrap long lines?

Anyway, it looks like this PR (together with #234 contains 2 modifications : typos and grammar, and reformat (fixed width). Maybe you could split these changes in 2 PR so that we can at least fix typos and grammar until even if we don't agree with the fixed with?

**Comment by muesli** [comment]
@JF002 I'll try to get to that, I just need to figure out how I can actually prevent my markdown editor from re-wrapping these lines :laughing:

**Comment by pfeerick** [comment]
Whilst there are  [pros and cons of wrapping and not wrapping](https://about.gitlab.com/blog/2016/10/11/wrapping-text/), I also prefer to let wrapping for text documentation at least to be handled by the viewer / editor... as that allows for the various screen sizes to be taken into account (code is different, especially Python because of those damn PEP8 style guide requirements). 

Out of curiosity though, I made a [simple markdown doc with some limited width text and running text](https://github.com/pfeerick/junkTester/blob/master/wordWrap.md) to double check, and both actually wrap to fit the screen width, because both the GitHub and GitLab Markdown renderer are looking for the double line break before a line break.

**Comment by muesli** [comment]
> Out of curiosity though, I made a [simple markdown doc with some limited width text and running text](https://github.com/pfeerick/junkTester/blob/master/wordWrap.md) to double check, and both actually wrap to fit the screen width, because both the GitHub and GitLab Markdown renderer are looking for the double line break before a line break.

That's what I've been pointing out twice in this thread already.

**Pull request closed without merging**
