### PR TITLE
Don't build the firmware when only docs were modified

### PR DESCRIPTION
**Pull request by Riksu9000**
No reason to run these checks in that case.

### CODE REVIEW

**Review by FintasticMan — CHANGES_REQUESTED** [review]
I think that the `.devcontainer`, `.idea`, `.vscode` and `hooks` directories can be excluded as well

**Review by JF002 — APPROVED** [review]

**Comment by Riksu9000** [comment]
> I think that the `.devcontainer`, `.idea`, `.vscode` and `hooks` directories can be excluded as well

I've been trying to think of another solution than explicitly mention multiple directories in multiple places, but haven't figured out a solution yet. I think it's best to just ignore the few directories that definitely don't have to do with code for now.

**Comment by FintasticMan** [comment]
> I've been trying to think of another solution than explicitly mention multiple directories in multiple places, but haven't figured out a solution yet.

All I can think of is still running the workflow, but checking if there is a file called something like `.nobuild` in the directory of the changes or any of its parents, and if so just saying that the test passed.

**Review by NeroBurner — APPROVED** [review]

**Comment by pfeerick** [comment]
You can also ignore by file extension... i.e. 
```
    paths-ignore:
      - '**.md'
 ```
 ignores changes to markdown files regardless of where in the repo ;)

**Pull request merged**
