### PR TITLE
Add pink color

### PR DESCRIPTION
**Pull request by Akselmo**
Hi, my first PR to this project :) 

My fiancee was absolutely devastated there was no proper pink color in the device, so I wanted to add it. 

Apparently this is the *true* pink color. :smile: 

image

She was happy with it, I hope you are too. :smile:

### CODE REVIEW

**Comment by Akselmo** [comment]
I think I am messing something up with the submodules. Should I just use `LV_COLOR_MAKE` instead of adding pink to lv_gl?

**Comment by Akselmo** [comment]
I changed it to `LV_COLOR_MAKE`. I've never used git submodules before so I hope I didn't mess anything up.

**Comment by minacode** [comment]
Two of your commits exclusively change LVGL. I guess they are the ones that break the build-test here. Maybe remove them or make a new clean PR?

**Comment by Akselmo** [comment]
> Two of your commits exclusively change LVGL. I guess they are the ones that break the build-test here. Maybe remove them or make a new clean PR?

Yeah I think I messed something up with the LVGL. I will make a new PR.

**Comment by Akselmo** [comment]
> Two of your commits exclusively change LVGL. I guess they are the ones that break the build-test here. Maybe remove them or make a new clean PR?

Here is the new PR https://github.com/InfiniTimeOrg/InfiniTime/pull/1325

**Pull request closed without merging**
