### PR TITLE
ci: Normalise slash-containing `github.head_ref` values

### PR DESCRIPTION
**Pull request by shymega**
This fixes CI on #2121.

### CODE REVIEW

**Comment by shymega** [comment]
@mark9064 If you could run the workflow one more time - I was testing in zsh locally, not bash - tested in bash with the recent force-push, and it works locally. Should be fine now.

**Comment by mark9064** [comment]
No worries, CI development is the worst because testing in prod is basically the only way :P

**Comment by shymega** [comment]
One more time - then if that fails, I'll take a look either before or after working hours today.

**Comment by FintasticMan** [comment]
I think you might need to escape the forward slash in the substitution. I.e. `${ref_name//\//-}`

**Comment by shymega** [comment]
On 15.11.2024 06:30, FintasticMan wrote:
>I think you might need to escape the forward slash in the substitution. I.e. `${ref_name//\//-}`

The latest push should have the above implemented.

Best wishes,
--
Dom Rodriguez

**Review by FintasticMan — CHANGES_REQUESTED** [review]
You've replaced `github.head_ref` with `github.ref_name`, meaning that the output is different.

**Review by FintasticMan — APPROVED** [review]
Looks good to me now!

**Comment by shymega** [comment]
Excellent! Once we get this landed, I'll rebase #2121 - and then we can merge that, too!

**Review by JF002 — APPROVED** [review]

**Comment by JF002** [comment]
Thanks for your contribution @shymega

**Pull request merged**
